data:
  in_memory: 1
  num_workers: 64
  train_dataset: /fsx/users/feisi/repos/experiments/ffcv-imagenet/train_500_0.50_90.ffcv 
  val_dataset: /fsx/users/feisi/repos/experiments/ffcv-imagenet/val_500_0.50_90.ffcv
dist:
  world_size: 8
logging:
  folder: /tmp/
  log_level: 1
lr:
  lr: 0.5
  lr_peak_epoch: 2
  lr_schedule_type: cyclic
model:
  arch: resnet18
resolution:
  max_res: 224
  min_res: 224
training:
  batch_size: 1024
  bn_wd: 0
  distributed: 1
  epochs: 300
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 5e-5
validation:
  lr_tta: true
  resolution: 256
